name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
      - run: shards install
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_crystal_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: crystal src/example.cr
